#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = xconfig_empty_min
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/utils.js:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/utils.js
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/xdc.tci:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/xdc.tci
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/template.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/template.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/om2.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/om2.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/xmlgen.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/xmlgen.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/xmlgen2.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/xmlgen2.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/Warnings.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/Warnings.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/IPackage.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/IPackage.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/package.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/package.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/global/Clock.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/global/Clock.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/global/Trace.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/global/Trace.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/bld.js:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/bld.js
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/BuildEnvironment.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/PackageContents.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/PackageContents.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/_gen.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/_gen.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Library.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Library.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Executable.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Executable.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Repository.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Repository.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Configuration.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Configuration.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Script.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Script.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Manifest.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Manifest.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Utils.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/Utils.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget2.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget2.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget3.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITarget3.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/ITargetFilter.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/package.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/bld/package.xs
package.mak: config.bld
/home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/ITarget.xs:
package.mak: /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/ITarget.xs
/home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/C28_large.xs:
package.mak: /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/C28_large.xs
/home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/C28_float.xs:
package.mak: /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/C28_float.xs
/home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/package.xs:
package.mak: /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/package.xs
/home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/arm/elf/IArm.xs
/home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/arm/elf/package.xs:
package.mak: /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/io/File.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/io/File.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/io/package.xs:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/services/io/package.xs
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /home/craig/lib/ti/xdctools_3_32_01_22_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.arm.elf.M3.rootDir ?= /home/craig/lib/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.1.LTS
ti.targets.arm.elf.packageBase ?= /home/craig/ti/tirtos_cc13xx_cc26xx_2_21_00_06/products/bios_6_46_01_37/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_xconfig_empty_min.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package xconfig_empty_min" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,em3 .dlls: empty_min.pem3

-include package/cfg/empty_min_pem3.mak
-include package/cfg/empty_min_pem3.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/empty_min_pem3.dep
endif
empty_min.pem3: package/cfg/empty_min_pem3.xdl
	@


ifeq (,$(wildcard .libraries,em3))
empty_min.pem3 package/cfg/empty_min_pem3.c: .libraries,em3
endif

package/cfg/empty_min_pem3.c package/cfg/empty_min_pem3.h package/cfg/empty_min_pem3.xdl: override _PROG_NAME := empty_min.xem3
package/cfg/empty_min_pem3.c: package/cfg/empty_min_pem3.cfg
package/cfg/empty_min_pem3.xdc.inc: package/cfg/empty_min_pem3.xdl
package/cfg/empty_min_pem3.xdl package/cfg/empty_min_pem3.c: .interfaces

clean:: clean,em3
	-$(RM) package/cfg/empty_min_pem3.cfg
	-$(RM) package/cfg/empty_min_pem3.dep
	-$(RM) package/cfg/empty_min_pem3.c
	-$(RM) package/cfg/empty_min_pem3.xdc.inc

clean,em3::
	-$(RM) empty_min.pem3
.executables,em3 .executables: empty_min.xem3

empty_min.xem3: |empty_min.pem3

-include package/cfg/empty_min.xem3.mak
empty_min.xem3: package/cfg/empty_min_pem3.oem3 
	$(RM) $@
	@$(MSG) lnkem3 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -fs $(XDCCFGDIR)$(dir $@) -q -u _c_int00 --silicon_version=7M3 -z --strict_compatibility=on  -o $@ package/cfg/empty_min_pem3.oem3   package/cfg/empty_min_pem3.xdl  -w -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.arm.elf.M3.rootDir)/lib/libc.a
	
empty_min.xem3: export C_DIR=
empty_min.xem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

empty_min.test test,em3 test: empty_min.xem3.test

empty_min.xem3.test:: empty_min.xem3
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 empty_min.xem3.test
else
	@$(MSG) running $<  ...
	$(call EXEC.empty_min.xem3, ) 
endif

clean,em3::
	-$(RM) $(wildcard .tmp,empty_min.xem3,*)


clean:: clean,em3

clean,em3::
	-$(RM) empty_min.xem3
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
empty_min_pem3.oem3,copy : package/cfg/empty_min_pem3.oem3
empty_min_pem3.sem3,copy : package/cfg/empty_min_pem3.sem3

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,xconfig_empty_min
ifeq (,$(MK_NOGENDEPS))
-include package/rel/xconfig_empty_min.tar.dep
endif
package/rel/xconfig_empty_min/xconfig_empty_min/package/package.rel.xml: package/package.bld.xml
package/rel/xconfig_empty_min/xconfig_empty_min/package/package.rel.xml: package/build.cfg
package/rel/xconfig_empty_min/xconfig_empty_min/package/package.rel.xml: package/package.xdc.inc
package/rel/xconfig_empty_min/xconfig_empty_min/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

xconfig_empty_min.tar: package/rel/xconfig_empty_min.xdc.inc package/rel/xconfig_empty_min/xconfig_empty_min/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/xconfig_empty_min.xdc.inc,package/rel/xconfig_empty_min.tar.dep)


release release,xconfig_empty_min: all xconfig_empty_min.tar
clean:: .clean
	-$(RM) xconfig_empty_min.tar
	-$(RM) package/rel/xconfig_empty_min.xdc.inc
	-$(RM) package/rel/xconfig_empty_min.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
